# Generated by Django 4.0.6 on 2022-07-24 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_daterangeevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DateChoiceEvent',
        ),
    ]
