# Generated by Django 4.0.6 on 2022-07-24 16:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_choice_eventuser_event_mode_delete_daterangeevent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='date',
        ),
        migrations.AddField(
            model_name='choice',
            name='dt_from',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 24, 16, 49, 48, 360190, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='dt_to',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 24, 16, 49, 54, 839710, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
