# Generated by Django 4.0.6 on 2022-08-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_choice_date_choice_dt_from_choice_dt_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventuser',
            name='display_name',
            field=models.CharField(editable=False, max_length=180, unique=True),
        ),
    ]
