# Generated by Django 4.0.6 on 2022-08-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_eventuser_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='user',
        ),
        migrations.AddField(
            model_name='choice',
            name='user',
            field=models.ManyToManyField(to='events.eventuser'),
        ),
        migrations.AlterField(
            model_name='eventuser',
            name='display_name',
            field=models.CharField(max_length=180, unique=True),
        ),
    ]
