# Generated by Django 4.0.6 on 2022-08-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_eventuser_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventuser',
            name='display_name',
            field=models.CharField(max_length=180),
        ),
    ]
