# Generated by Django 4.1 on 2022-08-11 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_at']},
        ),
    ]
