variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

image: python:latest
cache:
  paths:
    - .cache/pip

before_script:
  - pip install flake8 coverage
  - pip install -r requirements.txt
  - python manage.py makemigrations
  - python manage.py migrate

stages:
  - lint
  - test

check-db:
  stage: lint
  script:
    - python -m flake8 --max-line-length=120 **/*.py

check-db:
  stage: test
  script:
    - python manage.py check

run-tests:
  stage: test
  script:
    - python -m coverage run -m manage test
    - python -m coverage report --show-miss --fail-under=100
